# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ytstorage_pb2 as ytstorage__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ytstorage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/ytstorage.StorageService/Health',
                request_serializer=ytstorage__pb2.HealthRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/ytstorage.StorageService/Stat',
                request_serializer=ytstorage__pb2.StatRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/ytstorage.StorageService/Exists',
                request_serializer=ytstorage__pb2.ExistsRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.Mkdirs = channel.unary_unary(
                '/ytstorage.StorageService/Mkdirs',
                request_serializer=ytstorage__pb2.MkdirsRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.MkdirsResponse.FromString,
                _registered_method=True)
        self.Listdir = channel.unary_unary(
                '/ytstorage.StorageService/Listdir',
                request_serializer=ytstorage__pb2.ListdirRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.ListdirResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/ytstorage.StorageService/Rename',
                request_serializer=ytstorage__pb2.RenameRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.RenameResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/ytstorage.StorageService/Remove',
                request_serializer=ytstorage__pb2.RemoveRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.RemoveResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_stream(
                '/ytstorage.StorageService/Read',
                request_serializer=ytstorage__pb2.ReadRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.ReadChunk.FromString,
                _registered_method=True)
        self.Write = channel.stream_stream(
                '/ytstorage.StorageService/Write',
                request_serializer=ytstorage__pb2.WriteEnvelope.SerializeToString,
                response_deserializer=ytstorage__pb2.WriteAck.FromString,
                _registered_method=True)
        self.GeneratePresignedUrl = channel.unary_unary(
                '/ytstorage.StorageService/GeneratePresignedUrl',
                request_serializer=ytstorage__pb2.GenerateUrlRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.GenerateUrlResponse.FromString,
                _registered_method=True)
        self.EnqueuePut = channel.unary_unary(
                '/ytstorage.StorageService/EnqueuePut',
                request_serializer=ytstorage__pb2.EnqueuePutRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.JobRef.FromString,
                _registered_method=True)
        self.EnqueueGet = channel.unary_unary(
                '/ytstorage.StorageService/EnqueueGet',
                request_serializer=ytstorage__pb2.EnqueueGetRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.JobRef.FromString,
                _registered_method=True)
        self.JobStatus = channel.unary_unary(
                '/ytstorage.StorageService/JobStatus',
                request_serializer=ytstorage__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/ytstorage.StorageService/CancelJob',
                request_serializer=ytstorage__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=ytstorage__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdirs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Streaming:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePresignedUrl(self, request, context):
        """Direct Access:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueuePut(self, request, context):
        """Jobs / queues:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ytstorage__pb2.HealthRequest.FromString,
                    response_serializer=ytstorage__pb2.HealthResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=ytstorage__pb2.StatRequest.FromString,
                    response_serializer=ytstorage__pb2.StatResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=ytstorage__pb2.ExistsRequest.FromString,
                    response_serializer=ytstorage__pb2.ExistsResponse.SerializeToString,
            ),
            'Mkdirs': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdirs,
                    request_deserializer=ytstorage__pb2.MkdirsRequest.FromString,
                    response_serializer=ytstorage__pb2.MkdirsResponse.SerializeToString,
            ),
            'Listdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Listdir,
                    request_deserializer=ytstorage__pb2.ListdirRequest.FromString,
                    response_serializer=ytstorage__pb2.ListdirResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=ytstorage__pb2.RenameRequest.FromString,
                    response_serializer=ytstorage__pb2.RenameResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=ytstorage__pb2.RemoveRequest.FromString,
                    response_serializer=ytstorage__pb2.RemoveResponse.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=ytstorage__pb2.ReadRequest.FromString,
                    response_serializer=ytstorage__pb2.ReadChunk.SerializeToString,
            ),
            'Write': grpc.stream_stream_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=ytstorage__pb2.WriteEnvelope.FromString,
                    response_serializer=ytstorage__pb2.WriteAck.SerializeToString,
            ),
            'GeneratePresignedUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePresignedUrl,
                    request_deserializer=ytstorage__pb2.GenerateUrlRequest.FromString,
                    response_serializer=ytstorage__pb2.GenerateUrlResponse.SerializeToString,
            ),
            'EnqueuePut': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueuePut,
                    request_deserializer=ytstorage__pb2.EnqueuePutRequest.FromString,
                    response_serializer=ytstorage__pb2.JobRef.SerializeToString,
            ),
            'EnqueueGet': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueGet,
                    request_deserializer=ytstorage__pb2.EnqueueGetRequest.FromString,
                    response_serializer=ytstorage__pb2.JobRef.SerializeToString,
            ),
            'JobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.JobStatus,
                    request_deserializer=ytstorage__pb2.JobStatusRequest.FromString,
                    response_serializer=ytstorage__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=ytstorage__pb2.CancelJobRequest.FromString,
                    response_serializer=ytstorage__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytstorage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytstorage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Health',
            ytstorage__pb2.HealthRequest.SerializeToString,
            ytstorage__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Stat',
            ytstorage__pb2.StatRequest.SerializeToString,
            ytstorage__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Exists',
            ytstorage__pb2.ExistsRequest.SerializeToString,
            ytstorage__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdirs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Mkdirs',
            ytstorage__pb2.MkdirsRequest.SerializeToString,
            ytstorage__pb2.MkdirsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Listdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Listdir',
            ytstorage__pb2.ListdirRequest.SerializeToString,
            ytstorage__pb2.ListdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Rename',
            ytstorage__pb2.RenameRequest.SerializeToString,
            ytstorage__pb2.RenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/Remove',
            ytstorage__pb2.RemoveRequest.SerializeToString,
            ytstorage__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytstorage.StorageService/Read',
            ytstorage__pb2.ReadRequest.SerializeToString,
            ytstorage__pb2.ReadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ytstorage.StorageService/Write',
            ytstorage__pb2.WriteEnvelope.SerializeToString,
            ytstorage__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePresignedUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/GeneratePresignedUrl',
            ytstorage__pb2.GenerateUrlRequest.SerializeToString,
            ytstorage__pb2.GenerateUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueuePut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/EnqueuePut',
            ytstorage__pb2.EnqueuePutRequest.SerializeToString,
            ytstorage__pb2.JobRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/EnqueueGet',
            ytstorage__pb2.EnqueueGetRequest.SerializeToString,
            ytstorage__pb2.JobRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/JobStatus',
            ytstorage__pb2.JobStatusRequest.SerializeToString,
            ytstorage__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytstorage.StorageService/CancelJob',
            ytstorage__pb2.CancelJobRequest.SerializeToString,
            ytstorage__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
