# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import captions_pb2 as captions__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in captions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CaptionsServiceStub(object):
    """--- Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.stream_unary(
                '/ytcms.CaptionsService/Submit',
                request_serializer=captions__pb2.UploadChunk.SerializeToString,
                response_deserializer=captions__pb2.SubmitReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/ytcms.CaptionsService/GetStatus',
                request_serializer=captions__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=captions__pb2.JobStatusReply.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/ytcms.CaptionsService/StreamStatus',
                request_serializer=captions__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=captions__pb2.JobStatusReply.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/ytcms.CaptionsService/GetResult',
                request_serializer=captions__pb2.ResultRequest.SerializeToString,
                response_deserializer=captions__pb2.ResultReply.FromString,
                _registered_method=True)


class CaptionsServiceServicer(object):
    """--- Service
    """

    def Submit(self, request_iterator, context):
        """Stream load video.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """One-time status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Streaming status update (while the task is not completed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Getting the result (after status=done).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.stream_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=captions__pb2.UploadChunk.FromString,
                    response_serializer=captions__pb2.SubmitReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=captions__pb2.JobStatusRequest.FromString,
                    response_serializer=captions__pb2.JobStatusReply.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=captions__pb2.JobStatusRequest.FromString,
                    response_serializer=captions__pb2.JobStatusReply.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=captions__pb2.ResultRequest.FromString,
                    response_serializer=captions__pb2.ResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.CaptionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.CaptionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaptionsService(object):
    """--- Service
    """

    @staticmethod
    def Submit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ytcms.CaptionsService/Submit',
            captions__pb2.UploadChunk.SerializeToString,
            captions__pb2.SubmitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.CaptionsService/GetStatus',
            captions__pb2.JobStatusRequest.SerializeToString,
            captions__pb2.JobStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytcms.CaptionsService/StreamStatus',
            captions__pb2.JobStatusRequest.SerializeToString,
            captions__pb2.JobStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.CaptionsService/GetResult',
            captions__pb2.ResultRequest.SerializeToString,
            captions__pb2.ResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthStub(object):
    """==== Additions for ytadmin ====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/ytcms.Health/Check',
                request_serializer=captions__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=captions__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/ytcms.Health/Watch',
                request_serializer=captions__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=captions__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """==== Additions for ytadmin ====

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=captions__pb2.HealthCheckRequest.FromString,
                    response_serializer=captions__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=captions__pb2.HealthCheckRequest.FromString,
                    response_serializer=captions__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """==== Additions for ytadmin ====

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.Health/Check',
            captions__pb2.HealthCheckRequest.SerializeToString,
            captions__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytcms.Health/Watch',
            captions__pb2.HealthCheckRequest.SerializeToString,
            captions__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.All = channel.unary_unary(
                '/ytcms.Info/All',
                request_serializer=captions__pb2.InfoRequest.SerializeToString,
                response_deserializer=captions__pb2.InfoResponse.FromString,
                _registered_method=True)


class InfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def All(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'All': grpc.unary_unary_rpc_method_handler(
                    servicer.All,
                    request_deserializer=captions__pb2.InfoRequest.FromString,
                    response_serializer=captions__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.Info', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.Info', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Info(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def All(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.Info/All',
            captions__pb2.InfoRequest.SerializeToString,
            captions__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
