# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ytcms_pb2 as ytcms__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ytcms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CaptionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/ytcms.v1.CaptionsService/SubmitJob',
                request_serializer=ytcms__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=ytcms__pb2.JobAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/ytcms.v1.CaptionsService/GetStatus',
                request_serializer=ytcms__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=ytcms__pb2.GetStatusReply.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/ytcms.v1.CaptionsService/GetResult',
                request_serializer=ytcms__pb2.GetResultRequest.SerializeToString,
                response_deserializer=ytcms__pb2.JobResult.FromString,
                _registered_method=True)
        self.DeleteCaptions = channel.unary_unary(
                '/ytcms.v1.CaptionsService/DeleteCaptions',
                request_serializer=ytcms__pb2.DeleteCaptionsRequest.SerializeToString,
                response_deserializer=ytcms__pb2.DeleteCaptionsReply.FromString,
                _registered_method=True)


class CaptionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitJob(self, request, context):
        """Fire-and-forget submit. Client stores job_id and polls status/result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Polling status (percent included).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Getting the result (after status=done).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCaptions(self, request, context):
        """Service-side delete of captions artifacts: {storage_rel}/captions (recursive)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=ytcms__pb2.SubmitJobRequest.FromString,
                    response_serializer=ytcms__pb2.JobAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ytcms__pb2.GetStatusRequest.FromString,
                    response_serializer=ytcms__pb2.GetStatusReply.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=ytcms__pb2.GetResultRequest.FromString,
                    response_serializer=ytcms__pb2.JobResult.SerializeToString,
            ),
            'DeleteCaptions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCaptions,
                    request_deserializer=ytcms__pb2.DeleteCaptionsRequest.FromString,
                    response_serializer=ytcms__pb2.DeleteCaptionsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.v1.CaptionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.v1.CaptionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaptionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.CaptionsService/SubmitJob',
            ytcms__pb2.SubmitJobRequest.SerializeToString,
            ytcms__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.CaptionsService/GetStatus',
            ytcms__pb2.GetStatusRequest.SerializeToString,
            ytcms__pb2.GetStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.CaptionsService/GetResult',
            ytcms__pb2.GetResultRequest.SerializeToString,
            ytcms__pb2.JobResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCaptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.CaptionsService/DeleteCaptions',
            ytcms__pb2.DeleteCaptionsRequest.SerializeToString,
            ytcms__pb2.DeleteCaptionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthStub(object):
    """keep health/info for ytadmin
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/ytcms.v1.Health/Check',
                request_serializer=ytcms__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ytcms__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/ytcms.v1.Health/Watch',
                request_serializer=ytcms__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ytcms__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """keep health/info for ytadmin
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=ytcms__pb2.HealthCheckRequest.FromString,
                    response_serializer=ytcms__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=ytcms__pb2.HealthCheckRequest.FromString,
                    response_serializer=ytcms__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.v1.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """keep health/info for ytadmin
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.Health/Check',
            ytcms__pb2.HealthCheckRequest.SerializeToString,
            ytcms__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytcms.v1.Health/Watch',
            ytcms__pb2.HealthCheckRequest.SerializeToString,
            ytcms__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.All = channel.unary_unary(
                '/ytcms.v1.Info/All',
                request_serializer=ytcms__pb2.InfoRequest.SerializeToString,
                response_deserializer=ytcms__pb2.InfoResponse.FromString,
                _registered_method=True)


class InfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def All(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'All': grpc.unary_unary_rpc_method_handler(
                    servicer.All,
                    request_deserializer=ytcms__pb2.InfoRequest.FromString,
                    response_serializer=ytcms__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcms.v1.Info', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcms.v1.Info', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Info(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def All(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcms.v1.Info/All',
            ytcms__pb2.InfoRequest.SerializeToString,
            ytcms__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
