# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: info.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninfo.proto\x12\x0egrpc.health.v1\"\x1f\n\x0bInfoRequest\x12\x10\n\x08selector\x18\x01 \x01(\t\"\xb9\x02\n\x0cInfoResponse\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06uptime\x18\x05 \x01(\t\x12\x38\n\x06labels\x18\x06 \x03(\x0b\x32(.grpc.health.v1.InfoResponse.LabelsEntry\x12:\n\x07metrics\x18\x07 \x03(\x0b\x32).grpc.health.v1.InfoResponse.MetricsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32H\n\x04Info\x12@\n\x03\x41ll\x12\x1b.grpc.health.v1.InfoRequest\x1a\x1c.grpc.health.v1.InfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFORESPONSE_LABELSENTRY']._loaded_options = None
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_INFORESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_INFOREQUEST']._serialized_start=30
  _globals['_INFOREQUEST']._serialized_end=61
  _globals['_INFORESPONSE']._serialized_start=64
  _globals['_INFORESPONSE']._serialized_end=377
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_start=284
  _globals['_INFORESPONSE_LABELSENTRY']._serialized_end=329
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_start=331
  _globals['_INFORESPONSE_METRICSENTRY']._serialized_end=377
  _globals['_INFO']._serialized_start=379
  _globals['_INFO']._serialized_end=451
# @@protoc_insertion_point(module_scope)
