# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yurtube.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'yurtube.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ryurtube.proto\x12\x07ytadmin\"S\n\x0fServiceIdentity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"\xb1\x02\n\x11PushHealthRequest\x12*\n\x08identity\x18\x01 \x01(\x0b\x32\x18.ytadmin.ServiceIdentity\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x36\n\x06\x63hecks\x18\x03 \x03(\x0b\x32&.ytadmin.PushHealthRequest.ChecksEntry\x12\x38\n\x07metrics\x18\x04 \x03(\x0b\x32\'.ytadmin.PushHealthRequest.MetricsEntry\x12\x0e\n\x06ts_iso\x18\x05 \x01(\t\x1a-\n\x0b\x43hecksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xd4\x01\n\x12PushEffConfRequest\x12*\n\x08identity\x18\x01 \x01(\x0b\x32\x18.ytadmin.ServiceIdentity\x12\x37\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\'.ytadmin.PushEffConfRequest.ConfigEntry\x12\x15\n\rredacted_keys\x18\x03 \x03(\t\x12\x13\n\x0b\x63onfig_hash\x18\x04 \x01(\t\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x07PushAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x87\x01\n\x0b\x41\x64minIngest\x12:\n\nPushHealth\x12\x1a.ytadmin.PushHealthRequest\x1a\x10.ytadmin.PushAck\x12<\n\x0bPushEffConf\x12\x1b.ytadmin.PushEffConfRequest\x1a\x10.ytadmin.PushAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yurtube_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHHEALTHREQUEST_CHECKSENTRY']._loaded_options = None
  _globals['_PUSHHEALTHREQUEST_CHECKSENTRY']._serialized_options = b'8\001'
  _globals['_PUSHHEALTHREQUEST_METRICSENTRY']._loaded_options = None
  _globals['_PUSHHEALTHREQUEST_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_PUSHEFFCONFREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_PUSHEFFCONFREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_SERVICEIDENTITY']._serialized_start=26
  _globals['_SERVICEIDENTITY']._serialized_end=109
  _globals['_PUSHHEALTHREQUEST']._serialized_start=112
  _globals['_PUSHHEALTHREQUEST']._serialized_end=417
  _globals['_PUSHHEALTHREQUEST_CHECKSENTRY']._serialized_start=324
  _globals['_PUSHHEALTHREQUEST_CHECKSENTRY']._serialized_end=369
  _globals['_PUSHHEALTHREQUEST_METRICSENTRY']._serialized_start=371
  _globals['_PUSHHEALTHREQUEST_METRICSENTRY']._serialized_end=417
  _globals['_PUSHEFFCONFREQUEST']._serialized_start=420
  _globals['_PUSHEFFCONFREQUEST']._serialized_end=632
  _globals['_PUSHEFFCONFREQUEST_CONFIGENTRY']._serialized_start=587
  _globals['_PUSHEFFCONFREQUEST_CONFIGENTRY']._serialized_end=632
  _globals['_PUSHACK']._serialized_start=634
  _globals['_PUSHACK']._serialized_end=672
  _globals['_ADMININGEST']._serialized_start=675
  _globals['_ADMININGEST']._serialized_end=810
# @@protoc_insertion_point(module_scope)
