# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ytcomments_pb2 as ytcomments__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ytcomments_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YtCommentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTop = channel.unary_unary(
                '/ytcomments.v1.YtComments/ListTop',
                request_serializer=ytcomments__pb2.ListTopRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.ListTopResponse.FromString,
                _registered_method=True)
        self.ListReplies = channel.unary_unary(
                '/ytcomments.v1.YtComments/ListReplies',
                request_serializer=ytcomments__pb2.ListRepliesRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.ListRepliesResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/ytcomments.v1.YtComments/Create',
                request_serializer=ytcomments__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.CreateCommentResponse.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/ytcomments.v1.YtComments/Edit',
                request_serializer=ytcomments__pb2.EditCommentRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.EditCommentResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ytcomments.v1.YtComments/Delete',
                request_serializer=ytcomments__pb2.DeleteCommentRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.DeleteCommentResponse.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/ytcomments.v1.YtComments/Restore',
                request_serializer=ytcomments__pb2.RestoreCommentRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.RestoreCommentResponse.FromString,
                _registered_method=True)
        self.GetCounts = channel.unary_unary(
                '/ytcomments.v1.YtComments/GetCounts',
                request_serializer=ytcomments__pb2.GetCountsRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.GetCountsResponse.FromString,
                _registered_method=True)
        self.Vote = channel.unary_unary(
                '/ytcomments.v1.YtComments/Vote',
                request_serializer=ytcomments__pb2.VoteRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GetMyVotes = channel.unary_unary(
                '/ytcomments.v1.YtComments/GetMyVotes',
                request_serializer=ytcomments__pb2.GetMyVotesRequest.SerializeToString,
                response_deserializer=ytcomments__pb2.GetMyVotesResponse.FromString,
                _registered_method=True)


class YtCommentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReplies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyVotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YtCommentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTop': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTop,
                    request_deserializer=ytcomments__pb2.ListTopRequest.FromString,
                    response_serializer=ytcomments__pb2.ListTopResponse.SerializeToString,
            ),
            'ListReplies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReplies,
                    request_deserializer=ytcomments__pb2.ListRepliesRequest.FromString,
                    response_serializer=ytcomments__pb2.ListRepliesResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ytcomments__pb2.CreateCommentRequest.FromString,
                    response_serializer=ytcomments__pb2.CreateCommentResponse.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=ytcomments__pb2.EditCommentRequest.FromString,
                    response_serializer=ytcomments__pb2.EditCommentResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ytcomments__pb2.DeleteCommentRequest.FromString,
                    response_serializer=ytcomments__pb2.DeleteCommentResponse.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=ytcomments__pb2.RestoreCommentRequest.FromString,
                    response_serializer=ytcomments__pb2.RestoreCommentResponse.SerializeToString,
            ),
            'GetCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCounts,
                    request_deserializer=ytcomments__pb2.GetCountsRequest.FromString,
                    response_serializer=ytcomments__pb2.GetCountsResponse.SerializeToString,
            ),
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=ytcomments__pb2.VoteRequest.FromString,
                    response_serializer=ytcomments__pb2.VoteResponse.SerializeToString,
            ),
            'GetMyVotes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyVotes,
                    request_deserializer=ytcomments__pb2.GetMyVotesRequest.FromString,
                    response_serializer=ytcomments__pb2.GetMyVotesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytcomments.v1.YtComments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytcomments.v1.YtComments', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YtComments(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/ListTop',
            ytcomments__pb2.ListTopRequest.SerializeToString,
            ytcomments__pb2.ListTopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/ListReplies',
            ytcomments__pb2.ListRepliesRequest.SerializeToString,
            ytcomments__pb2.ListRepliesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/Create',
            ytcomments__pb2.CreateCommentRequest.SerializeToString,
            ytcomments__pb2.CreateCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/Edit',
            ytcomments__pb2.EditCommentRequest.SerializeToString,
            ytcomments__pb2.EditCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/Delete',
            ytcomments__pb2.DeleteCommentRequest.SerializeToString,
            ytcomments__pb2.DeleteCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/Restore',
            ytcomments__pb2.RestoreCommentRequest.SerializeToString,
            ytcomments__pb2.RestoreCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/GetCounts',
            ytcomments__pb2.GetCountsRequest.SerializeToString,
            ytcomments__pb2.GetCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/Vote',
            ytcomments__pb2.VoteRequest.SerializeToString,
            ytcomments__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyVotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytcomments.v1.YtComments/GetMyVotes',
            ytcomments__pb2.GetMyVotesRequest.SerializeToString,
            ytcomments__pb2.GetMyVotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
