# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import yttrans_pb2 as yttrans__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yttrans_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLanguages = channel.unary_unary(
                '/yttrans.v1.Translator/ListLanguages',
                request_serializer=yttrans__pb2.ListLanguagesRequest.SerializeToString,
                response_deserializer=yttrans__pb2.ListLanguagesResponse.FromString,
                _registered_method=True)
        self.SubmitTranslate = channel.unary_unary(
                '/yttrans.v1.Translator/SubmitTranslate',
                request_serializer=yttrans__pb2.SubmitTranslateRequest.SerializeToString,
                response_deserializer=yttrans__pb2.JobAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/yttrans.v1.Translator/GetStatus',
                request_serializer=yttrans__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=yttrans__pb2.Status.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/yttrans.v1.Translator/GetResult',
                request_serializer=yttrans__pb2.GetResultRequest.SerializeToString,
                response_deserializer=yttrans__pb2.TranslationsResult.FromString,
                _registered_method=True)


class TranslatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTranslate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLanguages,
                    request_deserializer=yttrans__pb2.ListLanguagesRequest.FromString,
                    response_serializer=yttrans__pb2.ListLanguagesResponse.SerializeToString,
            ),
            'SubmitTranslate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTranslate,
                    request_deserializer=yttrans__pb2.SubmitTranslateRequest.FromString,
                    response_serializer=yttrans__pb2.JobAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=yttrans__pb2.GetStatusRequest.FromString,
                    response_serializer=yttrans__pb2.Status.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=yttrans__pb2.GetResultRequest.FromString,
                    response_serializer=yttrans__pb2.TranslationsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yttrans.v1.Translator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yttrans.v1.Translator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Translator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yttrans.v1.Translator/ListLanguages',
            yttrans__pb2.ListLanguagesRequest.SerializeToString,
            yttrans__pb2.ListLanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTranslate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yttrans.v1.Translator/SubmitTranslate',
            yttrans__pb2.SubmitTranslateRequest.SerializeToString,
            yttrans__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yttrans.v1.Translator/GetStatus',
            yttrans__pb2.GetStatusRequest.SerializeToString,
            yttrans__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yttrans.v1.Translator/GetResult',
            yttrans__pb2.GetResultRequest.SerializeToString,
            yttrans__pb2.TranslationsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
