# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ytconvert_pb2 as ytconvert__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ytconvert_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConverterStub(object):
    """------------------------------------------------------------
    Services
    ------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitConvert = channel.unary_unary(
                '/ytconvert.v1.Converter/SubmitConvert',
                request_serializer=ytconvert__pb2.SubmitConvertRequest.SerializeToString,
                response_deserializer=ytconvert__pb2.JobAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/ytconvert.v1.Converter/GetStatus',
                request_serializer=ytconvert__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=ytconvert__pb2.Status.FromString,
                _registered_method=True)
        self.GetPartialResult = channel.unary_unary(
                '/ytconvert.v1.Converter/GetPartialResult',
                request_serializer=ytconvert__pb2.GetPartialResultRequest.SerializeToString,
                response_deserializer=ytconvert__pb2.PartialConvertResult.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/ytconvert.v1.Converter/GetResult',
                request_serializer=ytconvert__pb2.GetResultRequest.SerializeToString,
                response_deserializer=ytconvert__pb2.ConvertResult.FromString,
                _registered_method=True)
        self.WatchJob = channel.unary_stream(
                '/ytconvert.v1.Converter/WatchJob',
                request_serializer=ytconvert__pb2.WatchJobRequest.SerializeToString,
                response_deserializer=ytconvert__pb2.JobEvent.FromString,
                _registered_method=True)


class ConverterServicer(object):
    """------------------------------------------------------------
    Services
    ------------------------------------------------------------

    """

    def SubmitConvert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartialResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitConvert': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitConvert,
                    request_deserializer=ytconvert__pb2.SubmitConvertRequest.FromString,
                    response_serializer=ytconvert__pb2.JobAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ytconvert__pb2.GetStatusRequest.FromString,
                    response_serializer=ytconvert__pb2.Status.SerializeToString,
            ),
            'GetPartialResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartialResult,
                    request_deserializer=ytconvert__pb2.GetPartialResultRequest.FromString,
                    response_serializer=ytconvert__pb2.PartialConvertResult.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=ytconvert__pb2.GetResultRequest.FromString,
                    response_serializer=ytconvert__pb2.ConvertResult.SerializeToString,
            ),
            'WatchJob': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchJob,
                    request_deserializer=ytconvert__pb2.WatchJobRequest.FromString,
                    response_serializer=ytconvert__pb2.JobEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytconvert.v1.Converter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytconvert.v1.Converter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Converter(object):
    """------------------------------------------------------------
    Services
    ------------------------------------------------------------

    """

    @staticmethod
    def SubmitConvert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytconvert.v1.Converter/SubmitConvert',
            ytconvert__pb2.SubmitConvertRequest.SerializeToString,
            ytconvert__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytconvert.v1.Converter/GetStatus',
            ytconvert__pb2.GetStatusRequest.SerializeToString,
            ytconvert__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartialResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytconvert.v1.Converter/GetPartialResult',
            ytconvert__pb2.GetPartialResultRequest.SerializeToString,
            ytconvert__pb2.PartialConvertResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytconvert.v1.Converter/GetResult',
            ytconvert__pb2.GetResultRequest.SerializeToString,
            ytconvert__pb2.ConvertResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytconvert.v1.Converter/WatchJob',
            ytconvert__pb2.WatchJobRequest.SerializeToString,
            ytconvert__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
