# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ytsprites_pb2 as ytsprites__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ytsprites_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpritesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/ytsprites.v1.Sprites/Submit',
                request_serializer=ytsprites__pb2.SubmitRequest.SerializeToString,
                response_deserializer=ytsprites__pb2.SubmitReply.FromString,
                _registered_method=True)
        self.WatchStatus = channel.unary_stream(
                '/ytsprites.v1.Sprites/WatchStatus',
                request_serializer=ytsprites__pb2.StatusRequest.SerializeToString,
                response_deserializer=ytsprites__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/ytsprites.v1.Sprites/GetResult',
                request_serializer=ytsprites__pb2.GetResultRequest.SerializeToString,
                response_deserializer=ytsprites__pb2.ResultReply.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/ytsprites.v1.Sprites/Cancel',
                request_serializer=ytsprites__pb2.CancelRequest.SerializeToString,
                response_deserializer=ytsprites__pb2.CancelReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ytsprites.v1.Sprites/Health',
                request_serializer=ytsprites__pb2.HealthRequest.SerializeToString,
                response_deserializer=ytsprites__pb2.HealthReply.FromString,
                _registered_method=True)


class SpritesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpritesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=ytsprites__pb2.SubmitRequest.FromString,
                    response_serializer=ytsprites__pb2.SubmitReply.SerializeToString,
            ),
            'WatchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStatus,
                    request_deserializer=ytsprites__pb2.StatusRequest.FromString,
                    response_serializer=ytsprites__pb2.StatusUpdate.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=ytsprites__pb2.GetResultRequest.FromString,
                    response_serializer=ytsprites__pb2.ResultReply.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=ytsprites__pb2.CancelRequest.FromString,
                    response_serializer=ytsprites__pb2.CancelReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ytsprites__pb2.HealthRequest.FromString,
                    response_serializer=ytsprites__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytsprites.v1.Sprites', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytsprites.v1.Sprites', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sprites(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytsprites.v1.Sprites/Submit',
            ytsprites__pb2.SubmitRequest.SerializeToString,
            ytsprites__pb2.SubmitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ytsprites.v1.Sprites/WatchStatus',
            ytsprites__pb2.StatusRequest.SerializeToString,
            ytsprites__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytsprites.v1.Sprites/GetResult',
            ytsprites__pb2.GetResultRequest.SerializeToString,
            ytsprites__pb2.ResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytsprites.v1.Sprites/Cancel',
            ytsprites__pb2.CancelRequest.SerializeToString,
            ytsprites__pb2.CancelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ytsprites.v1.Sprites/Health',
            ytsprites__pb2.HealthRequest.SerializeToString,
            ytsprites__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
